apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: native-aspnetmvcapp
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: aspnetmvcapp
      name: aspnetmvcapp
      template:
        ref: native-aspnetmvcapp
