kind: Secret
apiVersion: v1
metadata:
  name: gitea-auth
  annotations:
    tekton.dev/git-0: 'http://gitea-git.apps.ocp.jonkey.cc'
data:
  password: cmVkaGF0
  username: am9ua2V5
type: kubernetes.io/basic-auth
